# IP address and TCP port the server has to bind to
tcp:
    address: 192.168.1.11
    port: 1234

# SSL/TLS settings like JSSE provider, enabled protocol
# versions & cipher suites etc.
ssl:
    provider: BCJSSE
    protocols:
        - TLSv1.2
    cipher_suites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
        - TLS_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_256_CBC_SHA256
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_128_CBC_SHA256
    use_client_authentication: false

# properties of the key-store to be used by the server
key_store:
    path: empty-key-store.jks
    algorithm: JKS
    password: aardwark

# settings passed to KeyManagerFactory
key_manager:
    algorithm: PKIX
    provider: BCJSSE
