# IP address and TCP port the client has to connect to
tcp:
    address: 192.168.1.11
    port: 1234

# SSL/TLS settings like JSSE provider, enabled protocol
# versions & cipher suites etc.
ssl:
    provider: BCJSSE
    protocols:
        - TLSv1.2
    cipher_suites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
        - TLS_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_256_CBC_SHA256
    use_client_authentication: false

# properties of the trust-store to be used by the client
trust_store:
    path: trust-store.jks
    algorithm: JKS
    password: aardwark

# settings passed to TrustManagerFactory
trust_manager:
    algorithm: PKIX
    provider: BCJSSE
